// SHIPPING_STATUS tổng vận đơn
const SHIPPING_STATUS = {
    WAITING_FOR_PICKUP: 'WAITING_FOR_PICKUP',
    PICKUP_FAILED: 'PICKUP_FAILED',
    PICKED_UP: 'PICKED_UP',
    IN_WAREHOUSE: 'IN_WAREHOUSE',
    IN_TRANSIT: 'IN_TRANSIT',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    DELIVERY_FAILED: 'DELIVERY_FAILED',
    RETURNING: 'RETURNING',
    RETURNED: 'RETURNED',
    CANCELLED: 'CANCELLED',
    LOST: 'LOST',
    DAMAGED: 'DAMAGED',
    ON_HOLD: 'ON_HOLD',
};

// CHECKPOINT_STATUS trạng thái quét mã
const CHECKPOINT_STATUS = {
    PICKUP_SUCCESS: 'PICKUP_SUCCESS',
    PICKUP_FAILED: 'PICKUP_FAILED',
    ARRIVAL_WAREHOUSE: 'ARRIVAL_WAREHOUSE',
    DEPARTURE_WAREHOUSE: 'DEPARTURE_WAREHOUSE',
    IN_TRANSIT: 'IN_TRANSIT',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED_SUCCESS: 'DELIVERED_SUCCESS',
    DELIVERED_FAILED: 'DELIVERED_FAILED',
    RETURN_TO_SENDER: 'RETURN_TO_SENDER',
};

// Map CHECKPOINT_STATUS sang SHIPPING_STATUS
const CHECKPOINT_TO_SHIPPING_STATUS = {
    PICKUP_SUCCESS: SHIPPING_STATUS.PICKED_UP,
    PICKUP_FAILED: SHIPPING_STATUS.PICKUP_FAILED,
    ARRIVAL_WAREHOUSE: SHIPPING_STATUS.IN_WAREHOUSE,
    DEPARTURE_WAREHOUSE: SHIPPING_STATUS.IN_TRANSIT,
    IN_TRANSIT: SHIPPING_STATUS.IN_TRANSIT,
    OUT_FOR_DELIVERY: SHIPPING_STATUS.OUT_FOR_DELIVERY,
    DELIVERED_SUCCESS: SHIPPING_STATUS.DELIVERED,
    DELIVERED_FAILED: SHIPPING_STATUS.DELIVERY_FAILED,
    RETURN_TO_SENDER: SHIPPING_STATUS.RETURNING,
};

module.exports = {
    SHIPPING_STATUS,
    CHECKPOINT_STATUS,
    CHECKPOINT_TO_SHIPPING_STATUS,
}; 